### ISSUE TITLE
README.md tutorial issues

### ISSUE THREAD

**Issue by rgpimenta** [joseedil/ngspice-ccam#1]
1. In first command line an error occurs. 
```
Unable to locate package libxaw-dev.
```
Just replace with libxaw7-dev.

2. Before ./reconfigure, install admsXml:
```
git clone https://github.com/Qucs/ADMS
cd ADMS
./bootstrap.sh
./configure
make
sudo make install
```

3. Running make, it shows the following error message: 
```
admsXml: error while loading shared libraries: libadmsElement.so.0: cannot open shared object file: No such file or directory
```

**Comment by joseedil** [comment]
The configure script can't find ADMS libraries. Try the instructions I detailed on the [last commit](https://github.com/joseedil/ngspice-ccam/commit/bc28e104903726ac0ef55f74d25c755a01c6ea83).

**Comment by rgpimenta** [comment]
It's working now.
